indexer:
  enabled: true

dirs:
  projects/compute:
    workspaces:
      default: {}
      prod: 
        tags: ["prod"]

drift:
  enabled: true
  schedules:
    default:
      tag_query: ''
      schedule: hourly

apply_requirements:
  create_pending_apply_check: true
  checks:
    - tag_query: "prod"
      approved:
        enabled: true
        any_of: ["user:chrisnie-airtasker"]
      merge_conflicts:
        enabled: true
    - tag_query: ""  # fallback catch-all
      approved:
        enabled: false

hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::010438481177:role/terrateam"
      - type: env
        name: AWS_CONFIG_FILE
        cmd: ['echo', '$TERRATEAM_ROOT/.terrateam/.aws_config']
